In [1]:
import numpy as np

### Crear un vector con valores dentro del rango 10 a 49

In [3]:
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Invertir el vector

In [4]:
vec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### Crear una matriz 3x3 con valores de 0 a 8

In [6]:
tres_x_tres = np.arange(0, 9).reshape((3, 3))
print(tres_x_tres)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [7]:
a = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
print(a)
np.argwhere(a != 0)

[ 1  2  4  2  4  0  1  0  0  0 12  4  5  6  7  0]


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 6],
       [10],
       [11],
       [12],
       [13],
       [14]], dtype=int32)

### Crear una matriz identidad de 6x6

In [8]:
np.identity(6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Crear una matriz con valores al azar con forma 3x3x3 

In [9]:
r = np.random.random((3,3,3))
print(r)

[[[0.11327284 0.53087651 0.84937676]
  [0.37561631 0.28098184 0.22737439]
  [0.2368804  0.13468673 0.78227157]]

 [[0.38515736 0.1720119  0.07766359]
  [0.66222468 0.0195784  0.88363842]
  [0.44161947 0.61138695 0.17073763]]

 [[0.03927788 0.23674586 0.0980788 ]
  [0.80155506 0.70207577 0.43828493]
  [0.4346031  0.73571839 0.51053047]]]


### Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [10]:
# Minimo y maximo del array ( no indice )
minimo = np.min(r)
maximo = np.max(r)
print(minimo, maximo)

# Indice min y max del array
print("r.argmax = ", r.argmax())
print("r.argmin = ", r.argmin())


0.019578402710004994 0.8836384179322051
r.argmax =  14
r.argmin =  13


### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [15]:
m = np.ones(100).reshape((10, 10))
m[1:-1 , 1:-1] = 0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [26]:
np.zeros(25).reshape((5, 5)) + np.arange(5)
#np.tile(np.arange(5), 5).reshape((5, 5))




array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### Crear dos arreglos al azar A y B, verificar si son iguales

In [63]:
a = np.random.randint(5, size=(2,2))
b = np.random.randint(5, size=(2,2))
print(a)
print()
print(b)

[[1 3]
 [2 2]]

[[1 1]
 [4 1]]


In [64]:
a == b

array([[ True, False],
       [False, False]])

In [61]:
np.allclose(a, b)


False

In [66]:
np.array_equal(a, b)

False